Feature/intent to df transposed
GoogleCloudPlatform/dfcx-scrapi pull request #73
Opened 2022-07-20 00:10 UTC by MRyderOC

PR regarding Issue #72.
Better documentation.
As discussed better memory usage for intent_proto_to_df in  https://github.com/GoogleCloudPlatform/dfcx-scrapi/blob/6bb8b70b5660e3d5d416500df8aa9ae5506833b0/src/dfcx_scrapi/core/intents.py#L155

2022-08-15 18:37 UTC, kmaphoenix requested changes
@MRyderOC couple of minor changes then we should be good to go.

2022-08-15 18:37 UTC, kmaphoenix commented on src/dfcx_scrapi/core/intents.py
> +          obj (Intent protobuf)
@MRyderOC for documentation here, you can omit the types inside the docstring. The type is already provide in the function definition. This is how the remainder of the library is currently documented, so this provides consistency throughout the docs.

For example:
```
obj: Intent Protobuf
mode: The operational mode of the function which determines the output
  "basic" returns display name and training phrase as plain text.
  "advanced" returns training phrases broken out by parts with their parameters included.
```

2022-08-15 18:37 UTC, kmaphoenix commented on src/dfcx_scrapi/core/intents.py
> +          agent_id (str):
Same here. Omit the typing inside the docstring itself in favor of the type hints in the function definition to keep it consistent/clean

2022-08-15 22:44 UTC, MRyderOC commented
Changes have been made as we discussed.

2022-08-20 18:47 UTC, kmaphoenix approved these changes
LGTM

2022-08-20 18:48 UTC, merged